routerSimulator : Envelope.cpp Action.cpp Socket.cpp Route.cpp Message.cpp InterfaceKevin.cpp InterfacePaola.cpp RouterSimulator.cpp 
	g++ -std=c++11 -g Envelope.cpp Action.cpp Socket.cpp Route.cpp Message.cpp InterfaceKevin.cpp InterfacePaola.cpp RouterSimulator.cpp -o routerSimulator -lpthread

clean :
	rm -f *.o routerSimulator core
