routerSimulator : Envelope.cpp Route.cpp Message.cpp Interface.cpp main.cpp  
	g++ -std=c++11 -g Envelope.cpp Route.cpp Message.cpp Interface.cpp main.cpp -o routerSimulator

clean :
	rm -f *.o routerSimulator core
